server {
    # Слушаем порт 8443 внутри контейнера с поддержкой SSL
    listen 8443 ssl;
    server_name mnwok.ru; # Ваш домен

    # Пути к сертификатам ВНУТРИ контейнера
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}