name: Deploy Website

on:
  push:
    branches:
      - main

# Права доступа, необходимые для работы GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Исключаем конфликты при одновременных деплоях Pages
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Задача 1: Ваша существующая сборка и деплой на сервер
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /mnwok.github.io
            git pull origin main
            docker compose up -d --build
            docker image prune -f

  # Задача 2: Новый деплой в GitHub Pages из папки /site
  deploy-to-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Указываем, что корнем сайта для GitHub Pages должна стать папка /site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4